# Generated by Django 5.2.7 on 2025-10-29 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the task",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the task"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level of the task",
                        max_length=10,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Due date for the task", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "In Review"),
                            ("done", "Completed"),
                        ],
                        default="todo",
                        help_text="Current status of the task",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="tasks_task_status_4a0a95_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="tasks_task_priorit_a900d4_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="tasks_task_due_dat_bce847_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tasks_task_created_be1ba2_idx"
                    ),
                ],
            },
        ),
    ]
